//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carestream.AdmTramas.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLinea
    {
        public int Id { get; set; }
        public int IdLibroLog { get; set; }
        public int Linea { get; set; }
        public string Campo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual LibroLogExportDetalle LibroLogExportDetalle { get; set; }
    }
}
