//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carestream.AdmTramas.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibroLogExportDetalle
    {
        public LibroLogExportDetalle()
        {
            this.ErrorLineas = new HashSet<ErrorLinea>();
        }
    
        public int IdLibroLog { get; set; }
        public int Linea { get; set; }
        public short IdLibro { get; set; }
        public string Trama { get; set; }
        public byte Estado { get; set; }
    
        public virtual LibroLog LibroLog { get; set; }
        public virtual ICollection<ErrorLinea> ErrorLineas { get; set; }
    }
}
