//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carestream.AdmTramas.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibroMayor
    {
        public int IdLibroLog { get; set; }
        public int Linea { get; set; }
        public short IdLibro { get; set; }
        public System.DateTime FechaOperacion { get; set; }
        public string Glosa { get; set; }
        public string Estado { get; set; }
        public string codunicooperacion { get; set; }
        public string NumeroCorrelativo { get; set; }
        public decimal Debe { get; set; }
        public decimal Haber { get; set; }
        public string Periodo { get; set; }
        public string CodigoPlanCuenta { get; set; }
        public string CodigoCuentaContable { get; set; }
        public string CuoVentas { get; set; }
        public string CuoCompras { get; set; }
        public string CuoConsignaciones { get; set; }
    
        public virtual LibroLog LibroLog { get; set; }
    }
}
