//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carestream.AdmTramas.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroCompra
    {
        public int IdLibroLog { get; set; }
        public int Linea { get; set; }
        public short IdLibro { get; set; }
        public string NumeroOperacion { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public string TipoComprobante { get; set; }
        public string NumeroSerieComprobante { get; set; }
        public string AnioEmisionComprobante { get; set; }
        public string NumeroComprobante { get; set; }
        public string TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public string NombreRazonSocial { get; set; }
        public Nullable<decimal> BaseImponibleGravada { get; set; }
        public Nullable<decimal> IGVGravado { get; set; }
        public Nullable<decimal> BaseImponibleMixta { get; set; }
        public Nullable<decimal> IGVMixto { get; set; }
        public Nullable<decimal> BaseImponibleNoGravada { get; set; }
        public Nullable<decimal> IGVNoGravado { get; set; }
        public Nullable<decimal> AdquisicionNoGravada { get; set; }
        public Nullable<decimal> ISC { get; set; }
        public Nullable<decimal> OtrosTributos { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string ComprobanteNoDomiciliado { get; set; }
        public string NumeroConstancia { get; set; }
        public System.DateTime FechaEmisionConstancia { get; set; }
        public decimal TipoCambio { get; set; }
        public System.DateTime FechaOriginal { get; set; }
        public string TipoDocumentoOriginal { get; set; }
        public string NumeroSerieOriginal { get; set; }
        public string NumeroDocumentoOriginal { get; set; }
        public string Pago { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string Detraccion { get; set; }
        public Nullable<decimal> TasaDetraccion { get; set; }
        public Nullable<decimal> ImporteDetraccion { get; set; }
        public string Retencion { get; set; }
        public Nullable<decimal> ImporteRetencion { get; set; }
        public string MotivoRetencion { get; set; }
        public Nullable<decimal> RevisionTasa { get; set; }
        public Nullable<decimal> RevisionTipoCambio { get; set; }
        public string RevisionVerificacion { get; set; }
        public Nullable<decimal> BaseRevision { get; set; }
        public Nullable<decimal> IGVRevision { get; set; }
        public string TipoGasto { get; set; }
        public string Recepcion { get; set; }
        public string Comentario1 { get; set; }
        public string Comentario2 { get; set; }
        public string VB { get; set; }
        public Nullable<decimal> CompraGravadaPais { get; set; }
        public Nullable<decimal> CompraGravadaExterior { get; set; }
        public Nullable<decimal> CompraNoGravada { get; set; }
        public Nullable<decimal> IGVPais { get; set; }
        public Nullable<decimal> Exterior { get; set; }
        public Nullable<decimal> OtrosCargos { get; set; }
        public Nullable<decimal> Total1 { get; set; }
        public string Estado { get; set; }
        public string codigounicooperacion { get; set; }
        public string numerocorrelativo { get; set; }
        public string DUA { get; set; }
        public string ClasificacionBien { get; set; }
    
        public virtual LibroLog LibroLog { get; set; }
    }
}
