//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carestream.AdmTramas.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroVenta
    {
        public int IdLibroLog { get; set; }
        public int Linea { get; set; }
        public short IdLibro { get; set; }
        public Nullable<System.DateTime> FechaComprobante { get; set; }
        public string TipoComprobante { get; set; }
        public string SerieComprobante { get; set; }
        public string NumeroComprobante { get; set; }
        public string TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public string CodigoDocumento { get; set; }
        public string NombreRazonSocial { get; set; }
        public decimal ValorVentaOriginal { get; set; }
        public string Moneda { get; set; }
        public decimal TipoCambio { get; set; }
        public decimal VV { get; set; }
        public decimal IGV { get; set; }
        public decimal PV { get; set; }
        public Nullable<System.DateTime> FechaModificada { get; set; }
        public string TipoComprobanteModificado { get; set; }
        public string NumeroSerieModificado { get; set; }
        public string NumeroComprobanteModificado { get; set; }
        public decimal VVModificado { get; set; }
        public decimal IGVModificado { get; set; }
        public decimal PVModificado { get; set; }
        public string NumeroUnicoOperacion { get; set; }
        public decimal OperacionNoGravada { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public decimal ValorEmbarcadoExportacion { get; set; }
        public decimal OperacionGravada { get; set; }
        public string Numero { get; set; }
        public string NumeroCorrelativo { get; set; }
    
        public virtual LibroLog LibroLog { get; set; }
    }
}
