//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carestream.AdmTramas.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibroLog
    {
        public LibroLog()
        {
            this.LibroLogExportDetalles = new HashSet<LibroLogExportDetalle>();
            this.LibroDiarios = new HashSet<LibroDiario>();
            this.RegistroVentas = new HashSet<RegistroVenta>();
            this.RegistroCompras = new HashSet<RegistroCompra>();
            this.LibroMayors = new HashSet<LibroMayor>();
            this.LibroDiarioAgrupados = new HashSet<LibroDiarioAgrupado>();
            this.LibroDiarioDetalles = new HashSet<LibroDiarioDetalle>();
        }
    
        public int Id { get; set; }
        public short IdLibro { get; set; }
        public string NombreLibro { get; set; }
        public Nullable<System.DateTime> FechaCarga { get; set; }
        public Nullable<System.DateTime> FechaGeneracion { get; set; }
        public int Registros { get; set; }
        public string RUC { get; set; }
        public string IndicadorOperacion { get; set; }
        public string IndicadorMoneda { get; set; }
        public string IndicadorLibro { get; set; }
        public string TipoLog { get; set; }
        public Nullable<int> Errores { get; set; }
        public Nullable<System.DateTime> FechaPeriodo { get; set; }
    
        public virtual Libro Libro { get; set; }
        public virtual ICollection<LibroLogExportDetalle> LibroLogExportDetalles { get; set; }
        public virtual ICollection<LibroDiario> LibroDiarios { get; set; }
        public virtual ICollection<RegistroVenta> RegistroVentas { get; set; }
        public virtual ICollection<RegistroCompra> RegistroCompras { get; set; }
        public virtual ICollection<LibroMayor> LibroMayors { get; set; }
        public virtual ICollection<LibroDiarioAgrupado> LibroDiarioAgrupados { get; set; }
        public virtual ICollection<LibroDiarioDetalle> LibroDiarioDetalles { get; set; }
    }
}
