//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigraPle.DataAccess.Sql.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MigraPLE_Entities : DbContext
    {
        public MigraPLE_Entities()
            : base("name=MigraPLE_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Archivo> Archivo { get; set; }
        public virtual DbSet<MetaArchivo> MetaArchivo { get; set; }
        public virtual DbSet<MetaArchivoRegla> MetaArchivoRegla { get; set; }
        public virtual DbSet<Operacion> Operacion { get; set; }
        public virtual DbSet<OperacionDetalle> OperacionDetalle { get; set; }
        public virtual DbSet<Regla> Regla { get; set; }
        public virtual DbSet<TipoOperacion> TipoOperacion { get; set; }
        public virtual DbSet<TipoRegla> TipoRegla { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
