//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigraPle.DataAccess.Sql.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaArchivo
    {
        public MetaArchivo()
        {
            this.MetaArchivoRegla = new HashSet<MetaArchivoRegla>();
        }
    
        public int id { get; set; }
        public string campo { get; set; }
        public int indice { get; set; }
        public string campoImport { get; set; }
        public bool esFijo { get; set; }
        public string valorFijo { get; set; }
        public int idArchivo { get; set; }
    
        public virtual Archivo Archivo { get; set; }
        public virtual ICollection<MetaArchivoRegla> MetaArchivoRegla { get; set; }
    }
}
