//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigraPle.DataAccess.Sql.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operacion
    {
        public Operacion()
        {
            this.OperacionDetalle = new HashSet<OperacionDetalle>();
        }
    
        public int id { get; set; }
        public int idArchivo { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaOperacion { get; set; }
        public int idTipoOperacion { get; set; }
        public System.DateTime periodo { get; set; }
    
        public virtual Archivo Archivo { get; set; }
        public virtual TipoOperacion TipoOperacion { get; set; }
        public virtual ICollection<OperacionDetalle> OperacionDetalle { get; set; }
    }
}
