//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigraPle.DataAccess.Sql.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperacionDetalle
    {
        public int id { get; set; }
        public int idOperacion { get; set; }
        public string registro { get; set; }
    
        public virtual Operacion Operacion { get; set; }
    }
}
