//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigraPle.DataAccess.Sql.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regla
    {
        public Regla()
        {
            this.MetaArchivoRegla = new HashSet<MetaArchivoRegla>();
        }
    
        public int id { get; set; }
        public int idTipoRegla { get; set; }
        public string valor { get; set; }
    
        public virtual ICollection<MetaArchivoRegla> MetaArchivoRegla { get; set; }
        public virtual TipoRegla TipoRegla { get; set; }
    }
}
