//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigraPle.DataAccess.Sql.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoRegla
    {
        public TipoRegla()
        {
            this.Regla = new HashSet<Regla>();
        }
    
        public int id { get; set; }
        public string tipo { get; set; }
    
        public virtual ICollection<Regla> Regla { get; set; }
    }
}
