//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigraPle.DataAccess.Sql.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoOperacion
    {
        public TipoOperacion()
        {
            this.Operacion = new HashSet<Operacion>();
        }
    
        public int id { get; set; }
        public string tipo { get; set; }
    
        public virtual ICollection<Operacion> Operacion { get; set; }
    }
}
