//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigraPle.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Archivo()
        {
            this.Operacions = new HashSet<Operacion>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public int idMetaArchivo { get; set; }
    
        public virtual MetaArchivo MetaArchivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operacion> Operacions { get; set; }
    }
}
