//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigraPle.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaArchivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MetaArchivo()
        {
            this.Archivoes = new HashSet<Archivo>();
            this.MetaArchivoReglas = new HashSet<MetaArchivoRegla>();
        }
    
        public int id { get; set; }
        public string campo { get; set; }
        public int indice { get; set; }
        public string campoImport { get; set; }
        public int idMetaRegla { get; set; }
        public bool esFijo { get; set; }
        public string valorFijo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Archivo> Archivoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MetaArchivoRegla> MetaArchivoReglas { get; set; }
    }
}
