//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigraPle.Model.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MigraPLEEntities : DbContext
    {
        public MigraPLEEntities()
            : base("name=MigraPLEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Archivo> Archivoes { get; set; }
        public virtual DbSet<MetaArchivo> MetaArchivoes { get; set; }
        public virtual DbSet<Operacion> Operacions { get; set; }
        public virtual DbSet<Regla> Reglas { get; set; }
        public virtual DbSet<MetaArchivoRegla> MetaArchivoReglas { get; set; }
    }
}
