//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigraPle.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operacion
    {
        public int id { get; set; }
        public Nullable<int> idArchivo { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaOperacion { get; set; }
        public string tipoOperacion { get; set; }
        public System.DateTime Periodo { get; set; }
        public string InfoExport { get; set; }
        public string InfoImport { get; set; }
    
        public virtual Archivo Archivo { get; set; }
    }
}
